version: '3'



version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmqtarefa
    hostname: rabbitmqtarefa

    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dbtarefa
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./proj/listaDeTarefas-main/init.sql:/docker-entrypoint-initdb.d/init.sql



